### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by deadmantfa** [nenad-zivkovic/yii2-advanced-template#15]
Can you help me with the nginx configuration for this template.

I would like to have the following
www.example.com ->>> Frontend
www.example.com/backend/ ->>> Backend

I am unable to configure it and there is no resource I could find to get this done.

Kindly help.

**Comment by nenad-zivkovic** [comment]
Sorry but I am not system administrator. I have one project build on top of my yii2-basic-template running on nginx, but all configuration was done by my hosting providers. I made my app in localhost on apache and since clients requested nginx, my hosting providers did what is necessary to make it work. I think they made some kind of redirect to apache, where nginx is serving images and other assets, and apache is doing the rest, because pretty URL didn't want to work on nginx. This is the only resource that I have: http://www.yiiframework.com/doc-2.0/guide-start-installation.html#recommended-nginx-configuration. If you find some solution, please share. Good luck.

**Comment by HankBrown** [comment]
"pretty URL didn't want to work on nginx" ?
**Please say so right up front** so we do not spend the time it takes to get to this issue.
Looks great but no access to backend is a killer.
Not enough Yii experience to know what you intended by reading the code.
